### ISSUE TITLE
[Question/Discussion] What is a good workflow?

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/tdl-client-spec#5]
As I'm working thru https://github.com/julianghionoiu/tdl-client-java/pull/8#issuecomment-427738468 and thinking about it, for efficiency and correctness reasons, there should be a better way to do this to cover these use cases:

1) Projects that use `tdl-client-spec` and make changes to `tdl-client-spec` (branch out)
2) Projects that use `tdl-client-spec` make changes to itself (via new branch) and also make changes to `tdl-client-spec` (via new branch)

It is NOT an issue when:

Projects that use `tdl-client-spec` when they branch out but make no changes to `tdl-client-spec`

The issue here is CI/CD failing if it is not able to fulfill the tests specified in `tdl-client-spec`, unless we have a way to tell CI/CD, for _this change_ in the parent project use _this branch_ of `tdl-client-spec`.

Resolution to the above will help make it less challenging especially when changing multiple projects at the same time that use `tdl-client-spec`.

**Comment by julianghionoiu** [comment]
Changes to `tdl-client-spec` should be done separately from `tdl-client-*` and then merged.

**Comment by neomatrix369** [comment]
The issue with CI/CD failing and not getting an indication, we can test it out locally, but can be a bit tedious
